### ISSUE TITLE
Make _make_request method public

### ISSUE THREAD

**Issue by anuj-reef** [gifbitjapan/pytunes-reporter#10]
Currently, `_make_request` method is protected. Can we change it to `make_request` to make it public so we can make custom requests also?

**Comment by chason** [comment]
Hi, sorry its taken me so long to respond to this.
I'm not necessarily against this change, but I am curious as to what you need the make_request API to be public for in case the API needs to change in other ways.

**Comment by anuj-reef** [comment]
There are few use case when we want to process the response in different ways. For eg. We want to get the report and upload it to s3.

**Comment by chason** [comment]
Hi, this should be fixed now!
