### ISSUE TITLE
account variable not used to get reports

### ISSUE THREAD

**Issue by anuj-reef** [gifbitjapan/pytunes-reporter#6]
This is an great library. But it is not working when we have an access token which belongs to multiple accounts. Although you are taking account as parameter but not using it.

**Comment by anuj-reef** [comment]
`command = f'[p=Reporter.properties, {cmd_type.capitalize()}.{command}]'` should add an account_string.
`command = f'[p=Reporter.properties, a={self.account}, {cmd_type.capitalize()}.{command}]'`

**Comment by chason** [comment]
Hi @anuj-reef thanks for the feedback.

You are totally right! I will make a release asap to fix that.

**Comment by chason** [comment]
This is merged and released. Let me know if you have any problems!

**Comment by anuj-reef** [comment]
Thanks so much for resolving this so fast.
